Local date time
activity-time/activity pull request #21
Opened 2016-11-09 20:58 UTC by andreevym

2016-11-09 21:19 UTC, turgeniev commented on activity-rest/src/main/resources/db/migration/V1_9.11.2016_00.35__Alter_table_add_column.sql
> +ALTER TABLE Action ADD COLUMN REMIND_DATE VARBINARY(255);
тип данных для даты странный - TIMESTAMP же должен быть

2016-11-09 21:20 UTC, turgeniev requested changes
Тип данных для LocalDateTime должен быть TIMESTAMP (или аналог)

2016-11-12 20:18 UTC, andreevym commented
пока что не знаю как сделать в бд TIMESTAMP

2016-11-14 20:11 UTC, andreevym commented
Задача https://github.com/activity-time/activity/issues/5

2016-11-14 20:14 UTC, merged